### ISSUE TITLE
request for U.S. Cellular network support

### ISSUE THREAD

**Issue by jrcresawn** [mbmc/FiInfo#2]
Is there any chance you will add support for U.S. Cellular now that Project Fi has added that network?

https://fi.google.com/about/faq/#network-and-coverage-2

**Comment by jrcresawn** [comment]
Thank you for responding so quickly to my request for U.S. Cellular support! Will you push your code changes used to build the new app on the Play Store to this repository?

**Comment by mbmc** [comment]
Hi! Yes, I'll push the code soon. Thanks for using the app.
